# Plugins
# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'

source ~/.config/tmux/tmux.conf.local

run '~/.tmux/plugins/tpm/tpm'

# Tmux Powerline Theme
# git clone https://github.com/wfxr/tmux-power.git ~/.tmux/tmux-power
run-shell "~/.tmux/tmux-power/tmux-power.tmux"
